siteTitle="SF Art"
siteDescription="An collection of science fiction and fantasy art"
siteUrl= "http://sfart.co"
siteVersion= "1.0.0"
copyrightMessage= "<a href='http://damirvazgird.com' target='_blank'>Damir Vazgird</a>. Powered by <a href='http://withpulp.com' target='_blank'>With Pulp</a>."
linkPrefix= ""
#gaCode= "UA-42428554-1"
